# Generated by Django 3.1.5 on 2021-02-14 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210211_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
